version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8001
  
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: service_db
      POSTGRES_USER: 'django'
      POSTGRES_PASSWORD: 'django'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
