version: '3.9'

services:
  db:
    image: postgres:16
    container_name: service-db
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./app
    container_name: service-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: service_db
      DB_USER: django
      DB_PASSWORD: django
      DB_HOST: db

volumes:
  postgres_data:
