version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
    - AWS_REGION=ap-northeast-1

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: service_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

