# Generated by Django 6.0.7 on 2026-07-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_assignment_end_time_assignment_is_daily_reporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='slack_user_id',
            field=models.CharField(blank=True, default='', help_text='例: U0A1E588J2J', max_length=20, verbose_name='SlackユーザーID'),
        ),
    ]
