# Generated by Django 6.0.3 on 2026-07-23 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_rename_slack_app_token_office__slack_app_token_and_more'),
        ('employees', '0004_rename_employee_staff_can_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.office', verbose_name='所属事務所'),
        ),
    ]
