# Generated by Django 6.0.3 on 2026-09-20 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_remove_user_care_manager_and_more'),
        ('employees', '0005_staff_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboard.useuser', verbose_name='利用者'),
        ),
        migrations.AlterField(
            model_name='shiftpattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_patterns', to='dashboard.useuser', verbose_name='利用者'),
        ),
    ]
