# Generated by Django 4.2.30 on 2026-07-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('date', models.DateField(verbose_name='日付')),
                ('mood', models.CharField(choices=[('great', '😄 最高'), ('good', '🙂 良い'), ('normal', '😐 普通'), ('bad', '😞 いまいち'), ('terrible', '😢 最悪')], default='normal', max_length=10, verbose_name='気分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '日記',
                'verbose_name_plural': '日記',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
