# Generated by Django 4.2.30 on 2026-07-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/%Y/%m/', verbose_name='画像'),
        ),
    ]
