# Generated by Django 4.2.30 on 2026-07-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_entry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slack_ts',
            field=models.CharField(blank=True, editable=False, help_text='Slackから取り込んだメッセージの重複防止用ID', max_length=32, null=True, unique=True, verbose_name='Slackメッセージts'),
        ),
    ]
