# Generated by Django 6.0.6 on 2026-07-05 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_servicerecord_end_time_servicerecord_start_time_and_more'),
        ('diary', '0003_entry_slack_ts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '日報', 'verbose_name_plural': '日報'},
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.user', verbose_name='利用者'),
            preserve_default=False,
        ),
    ]
