# Generated by Django 6.0.3 on 2026-09-20 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_remove_user_care_manager_and_more'),
        ('diary', '0004_alter_entry_options_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.useuser', verbose_name='利用者'),
        ),
    ]
