# Generated by Django 6.0.3 on 2026-03-15 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_level', models.CharField(choices=[('要支護1', '要支護1'), ('要支護2', '要支護2'), ('要介護1', '要介護1'), ('要介護2', '要介護2'), ('要介護3', '要介護3'), ('要介護4', '要介護4'), ('要介護5', '要介護5')], max_length=10)),
                ('stay_time_category', models.CharField(choices=[('3-4', '3〜4時間'), ('4-5', '4〜5時間'), ('5-6', '5〜6時間'), ('6-7', '6〜7時間'), ('7-8', '7〜8時間')], max_length=20)),
                ('service_code', models.CharField(max_length=20)),
                ('unit', models.IntegerField()),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='被保険者氏名')),
                ('name_kana', models.CharField(max_length=100, verbose_name='フリガナ')),
                ('care_level', models.CharField(choices=[('要支護1', '要支護1'), ('要支護2', '要支護2'), ('要介護1', '要介護1'), ('要介護2', '要介護2'), ('要介護3', '要介護3'), ('要介護4', '要介護4'), ('要介護5', '要介護5')], max_length=10, verbose_name='要介護状態区分')),
                ('insured_number', models.CharField(blank=True, default='', max_length=10, verbose_name='被保険者番号')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], default='', max_length=10, verbose_name='性別')),
                ('notes', models.TextField(blank=True, default='', verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unit', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.servicemaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2024-01-01')),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='15:00')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
    ]
