# Generated by Django 6.0.3 on 2026-03-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='description',
            field=models.CharField(default='2024-01-01', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], default='female', max_length=10, verbose_name='性別'),
        ),
    ]
