# Generated by Django 6.0.3 on 2026-03-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_servicemaster_description_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_level', models.CharField(choices=[('要支護1', '要支護1'), ('要支護2', '要支護2'), ('要介護1', '要介護1'), ('要介護2', '要介護2'), ('要介護3', '要介護3'), ('要介護4', '要介護4'), ('要介護5', '要介護5')], max_length=10, verbose_name='要介護状態区分')),
                ('stay_time_category', models.CharField(choices=[('<3', '<3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9')], max_length=10)),
                ('service_category', models.CharField(max_length=15)),
                ('unit', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='end_time',
            field=models.TimeField(default='15:01'),
        ),
    ]
