# Generated by Django 6.0.3 on 2026-03-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_servicecategory_alter_serviceplan_end_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='stay_time_category',
            field=models.CharField(choices=[('<3', '<3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9')], max_length=20),
        ),
    ]
