# Generated by Django 6.0.3 on 2026-03-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_servicecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
