# Generated by Django 6.0.3 on 2026-03-20 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_servicemaster_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
    ]
