# Generated by Django 6.0.3 on 2026-03-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_serviceplan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='unit',
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='actual_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='schudule_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='pattern_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='pattern_type',
            field=models.CharField(choices=[('day', '日ごと'), ('week', '週ごと'), ('month', '各週ごと')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='stay_time_category',
            field=models.CharField(choices=[('<3', '3時間以下'), ('3-4', '3以上-4未満'), ('4-5', '4以上-5未満'), ('5-6', '5以上-6未満'), ('6-7', '6以上-7未満'), ('7-8', '7以上-8未満'), ('8-9', '8以上-9未満')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='end_time',
            field=models.TimeField(default='15:00'),
        ),
    ]
