# Generated by Django 6.0.3 on 2026-03-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_servicerecord_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceplan',
            old_name='schudule_json',
            new_name='schedule_json',
        ),
    ]
