# Generated by Django 6.0.3 on 2026-03-29 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_schudule_json_serviceplan_schedule_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('service_name', models.CharField(max_length=100)),
                ('unit', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('insurance_type', models.CharField(choices=[('insurance', '保険内'), ('self_pay', '保険外')], max_length=20)),
                ('apply_unit', models.CharField(choices=[('monthly', '月ごと'), ('per_day', '日ごと'), ('per_service', 'サービスごと')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceplan',
            name='date',
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='actual_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='schedule_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
        migrations.CreateModel(
            name='UserAddOnService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.addonservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
    ]
