# Generated by Django 6.0.3 on 2026-03-29 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_addonservice_remove_serviceplan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='description',
            field=models.CharField(default='2026-03-01', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='month',
            field=models.IntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], default=3),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='year',
            field=models.IntegerField(choices=[(2025, '2025年'), (2026, '2026年')], default=2026),
        ),
    ]
