# Generated by Django 6.0.3 on 2026-03-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_servicemaster_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonservice',
            name='medical_deduction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addonservice',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addonservice',
            name='tax_type',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
