# Generated by Django 6.0.3 on 2026-03-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_addonservice_medical_deduction_addonservice_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addonservice',
            old_name='tax_type',
            new_name='is_tax',
        ),
    ]
