# Generated by Django 6.0.3 on 2026-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_tax_type_addonservice_is_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonservice',
            name='apply_unit',
            field=models.CharField(blank=True, choices=[('monthly', '月ごと'), ('per_day', '日ごと'), ('per_service', 'サービスごと')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='medical_deduction',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
