# Generated by Django 6.0.3 on 2026-04-05 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_addonservice_apply_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonservice',
            name='apply_unit',
            field=models.CharField(blank=True, choices=[('monthly', '月ごと'), ('per_day', '日ごと'), ('per_service', 'サービスごと')], max_length=20, null=True, verbose_name='適用種類'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='insurance_type',
            field=models.CharField(choices=[('insurance', '保険内'), ('self_pay', '自費')], max_length=20, verbose_name='保険適用'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='is_tax',
            field=models.BooleanField(default=False, max_length=20, verbose_name='課税'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='medical_deduction',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='医療費控除対象'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='month',
            field=models.IntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], default=4),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
    ]
