# Generated by Django 6.0.3 on 2026-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_addonservice_apply_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='service_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='service_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
