# Generated by Django 6.0.4 on 2026-05-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_serviceplan_service_code_serviceplan_service_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_code', models.IntegerField(blank=True, choices=[(1, '1地域'), (2, '2地域'), (3, '3地域'), (4, '4地域'), (5, '5地域'), (6, '6地域'), (7, '7地域')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='addonservice',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='addonservice',
            name='type',
            field=models.CharField(blank=True, choices=[('unit', '単位'), ('rate', '率')], null=True),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='month',
            field=models.IntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], default=5),
        ),
    ]
