# Generated by Django 6.0.4 on 2026-05-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_addonservice_type_alter_office_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonservice',
            name='type',
            field=models.CharField(choices=[('unit', '単位'), ('rate', '率')]),
        ),
        migrations.AlterField(
            model_name='office',
            name='area_code',
            field=models.IntegerField(choices=[(1, '1地域'), (2, '2地域'), (3, '3地域'), (4, '4地域'), (5, '5地域'), (6, '6地域'), (7, '7地域')]),
        ),
    ]
