# Generated by Django 6.0.4 on 2026-05-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_addonservice_type_alter_office_area_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='defalt_service',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
