# Generated by Django 6.0.4 on 2026-05-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_office_defalt_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='burden_rate',
            field=models.IntegerField(choices=[(1, '1割'), (2, '2割'), (3, '3割')], default=1),
        ),
    ]
