# Generated by Django 6.0.4 on 2026-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_user_burden_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='service_type_code',
            field=models.IntegerField(choices=[(78, '地域密着型通所介護'), (79, '通所介護（通常規模）'), (80, '通所介護（大規模Ⅰ）'), (81, '通所介護（大規模Ⅱ）')], default=78),
        ),
        migrations.AlterField(
            model_name='user',
            name='burden_rate',
            field=models.IntegerField(choices=[(1, '1割'), (2, '2割'), (3, '3割')], default=1, verbose_name='負担割合'),
        ),
    ]
