# Generated by Django 6.0.4 on 2026-05-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_office_service_type_code_alter_user_burden_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_code', models.CharField(max_length=6, unique=True)),
                ('prefecture', models.CharField(blank=True, max_length=50, null=True, verbose_name='都道府県')),
                ('name', models.CharField(max_length=50, verbose_name='市区町村')),
                ('area_grade', models.IntegerField(choices=[(1, '1地域'), (2, '2地域'), (3, '3地域'), (4, '4地域'), (5, '5地域'), (6, '6地域'), (7, '7地域')], verbose_name='地域区分')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='benefit_rate',
            field=models.FloatField(choices=[(0.9, '給付率90%（1割負担）'), (0.8, '給付率80%（2割負担）'), (0.7, '給付率70%（3割負担）')], default=0.9),
        ),
        migrations.AlterField(
            model_name='office',
            name='area_code',
            field=models.IntegerField(choices=[(1, '1地域'), (2, '2地域'), (3, '3地域'), (4, '4地域'), (5, '5地域'), (6, '6地域'), (7, '7地域')], verbose_name='地域区分'),
        ),
        migrations.AlterField(
            model_name='office',
            name='service_type_code',
            field=models.IntegerField(choices=[(78, '地域密着型通所介護'), (79, '通所介護（通常規模）'), (80, '通所介護（大規模Ⅰ）'), (81, '通所介護（大規模Ⅱ）')], default=78, verbose_name='種類コード'),
        ),
        migrations.DeleteModel(
            name='UserAddOnService',
        ),
    ]
