# Generated by Django 6.0.4 on 2026-05-06 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_municipality_user_benefit_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='municipality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.municipality'),
            preserve_default=False,
        ),
    ]
