# Generated by Django 6.0.4 on 2026-05-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_office_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='benefit_rate',
            field=models.FloatField(choices=[(0.9, '給付率90%（1割負担）'), (0.8, '給付率80%（2割負担）'), (0.7, '給付率70%（3割負担）')], verbose_name='給付率'),
        ),
    ]
