# Generated by Django 6.0.4 on 2026-05-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_user_benefit_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='defalt_service',
            field=models.IntegerField(blank=True, default='112300', max_length=6, null=True),
        ),
    ]
