# Generated by Django 6.0.4 on 2026-05-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_office_defalt_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='defalt_service',
            field=models.IntegerField(default=1, verbose_name='保険者番号(地域)'),
            preserve_default=False,
        ),
    ]
