# Generated by Django 6.0.4 on 2026-05-07 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_office_defalt_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='defalt_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.addonservice'),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(verbose_name='保険者番号'),
        ),
    ]
