# Generated by Django 6.0.4 on 2026-05-07 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_office_defalt_service_alter_office_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.municipality', verbose_name='保険者番号'),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
