# Generated by Django 6.0.4 on 2026-05-07 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_office_municipality_alter_office_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_kana', models.CharField(blank=True, max_length=100, null=True)),
                ('office_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='municipality',
            name='municipality_code',
            field=models.CharField(max_length=6, unique=True, verbose_name='保険者番号'),
        ),
        migrations.AlterField(
            model_name='office',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.municipality'),
        ),
    ]
