# Generated by Django 6.0.4 on 2026-05-07 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_caremanager_alter_municipality_municipality_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caremanager',
            name='name_kana',
        ),
        migrations.AddField(
            model_name='user',
            name='care_manager',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.caremanager'),
        ),
    ]
