# Generated by Django 6.0.4 on 2026-05-07 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_caremanager_name_kana_user_care_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='care_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.caremanager'),
        ),
    ]
