# Generated by Django 6.0.4 on 2026-05-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_user_care_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caremanager',
            old_name='phone',
            new_name='tel',
        ),
        migrations.AlterField(
            model_name='caremanager',
            name='name',
            field=models.CharField(max_length=100, verbose_name='担当者名'),
        ),
        migrations.AlterField(
            model_name='caremanager',
            name='office_name',
            field=models.CharField(max_length=200, verbose_name='居宅介護支援事業所名'),
        ),
    ]
