# Generated by Django 6.0.4 on 2026-05-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_rename_phone_caremanager_tel_alter_caremanager_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='defalt_service',
            new_name='default_service',
        ),
        migrations.AddField(
            model_name='office',
            name='office_number',
            field=models.IntegerField(default=1175101250),
            preserve_default=False,
        ),
    ]
