# Generated by Django 6.0.4 on 2026-05-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_rename_defalt_service_office_default_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='burden_rate',
        ),
        migrations.AddField(
            model_name='caremanager',
            name='care_management_office_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='居宅介護支援事業所番号'),
        ),
        migrations.AddField(
            model_name='caremanager',
            name='care_manager_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='居宅介護支援専門員番号'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
