# Generated by Django 6.0.4 on 2026-05-09 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_remove_user_burden_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='area_code',
        ),
    ]
