# Generated by Django 6.0.4 on 2026-05-09 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_remove_office_area_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_status', models.CharField(choices=[('申請中', '申請中'), ('認定済み', '認定済み')], max_length=10, verbose_name='認定状態')),
                ('insured_number', models.CharField(max_length=10, verbose_name='被保険者番号（10桁）')),
                ('care_level', models.CharField(choices=[('要支援1', '要支援1'), ('要支援2', '要支援2'), ('要介護1', '要介護1'), ('要介護2', '要介護2'), ('要介護3', '要介護3'), ('要介護4', '要介護4'), ('要介護5', '要介護5')], max_length=10, verbose_name='要介護状態区分')),
                ('care_level_changed_at', models.DateField(blank=True, null=True, verbose_name='要介護状態区分変更日')),
                ('benefit_rate', models.FloatField(choices=[(0.9, '給付率90%（1割負担）'), (0.8, '給付率80%（2割負担）'), (0.7, '給付率70%（3割負担）')], verbose_name='給付率')),
                ('benefit_limit_flag', models.BooleanField(default=False, verbose_name='給付制限')),
                ('limit_amount_type', models.CharField(choices=[('規定', '規定通り'), ('任意', '任意設定')], max_length=10, verbose_name='区分支給限度基準額区分')),
                ('limit_amount_value', models.IntegerField(blank=True, null=True, verbose_name='任意設定の限度額')),
                ('limit_start', models.DateField(verbose_name='限度額適用開始日')),
                ('limit_end', models.DateField(blank=True, null=True, verbose_name='限度額適用終了日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='dashboard.user', verbose_name='利用者')),
            ],
        ),
    ]
