# Generated by Django 6.0.4 on 2026-05-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_insurancecertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='care_level',
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='care_level',
            field=models.CharField(choices=[('要支援1', '要支援1'), ('要支援2', '要支援2'), ('要介護1', '要介護1'), ('要介護2', '要介護2'), ('要介護3', '要介護3'), ('要介護4', '要介護4'), ('要介護5', '要介護5')], max_length=10),
        ),
    ]
