# Generated by Django 6.0.4 on 2026-05-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_remove_user_care_level_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsuranceCertificate',
            new_name='Certificate',
        ),
    ]
