# Generated by Django 6.0.4 on 2026-05-09 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_rename_insurancecertificate_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='recognition_status',
            field=models.CharField(choices=[('0', '消去'), ('申請中', '申請中'), ('認定済み', '認定済み')], max_length=10, verbose_name='認定状態'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='dashboard.user', verbose_name='利用者'),
        ),
    ]
