# Generated by Django 6.0.4 on 2026-05-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_certificate_recognition_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='recognition_status',
        ),
    ]
