# Generated by Django 6.0.4 on 2026-05-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_remove_certificate_recognition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='limit_end',
            field=models.DateField(verbose_name='限度額適用終了日'),
        ),
    ]
