# Generated by Django 6.0.4 on 2026-05-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_certificate_limit_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRecord',
        ),
    ]
