# Generated by Django 6.0.4 on 2026-05-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_servicerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='insured_number',
            field=models.CharField(max_length=10, verbose_name='被保険者番号'),
        ),
    ]
