# Generated by Django 6.0.6 on 2026-06-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_alter_user_date_of_birth_alter_user_insured_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caremanager',
            name='care_management_office_number',
            field=models.CharField(default=111, max_length=20, verbose_name='居宅介護支援事業所番号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='month',
            field=models.IntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], default=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=10, verbose_name='性別'),
        ),
    ]
