# Generated by Django 6.0.6 on 2026-07-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_alter_user_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicerecord',
            unique_together={('user', 'date')},
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='weekday_pattern',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='limit_amount_type',
            field=models.CharField(choices=[('規定', '規定通り'), ('任意', '任意設定')], default='規定', max_length=10, verbose_name='区分支給限度基準額区分'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='month',
            field=models.IntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], default=7),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='date',
            field=models.DateField(help_text='月初の日付（例: 2026-07-01）'),
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='pattern_json',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='pattern_type',
        ),
    ]
