# Generated by Django 6.0.6 on 2026-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_alter_servicerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='insured_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='被保険者番号'),
        ),
    ]
