# Generated by Django 6.0.6 on 2026-07-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_alter_user_insured_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='care_level',
            field=models.CharField(choices=[('要介護1', '要介護1'), ('要介護2', '要介護2'), ('要介護3', '要介護3'), ('要介護4', '要介護4'), ('要介護5', '要介護5')], max_length=10, verbose_name='要介護状態区分'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='care_level',
            field=models.CharField(choices=[('要介護1', '要介護1'), ('要介護2', '要介護2'), ('要介護3', '要介護3'), ('要介護4', '要介護4'), ('要介護5', '要介護5')], max_length=10),
        ),
    ]
