# Generated by Django 6.0.7 on 2026-07-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_servicerecord_end_time_servicerecord_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='benefit_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='over_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='over_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='over_user_share',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='user_share_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='within_units',
            field=models.IntegerField(default=0),
        ),
    ]
