# Generated by Django 6.0.7 on 2026-07-21 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_servicerecord_benefit_amount_servicerecord_over_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMonthlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateField(blank=True, null=True, verbose_name='確定日')),
                ('date', models.DateField(help_text='月初の日付（例: 2026-07-01）')),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('weekday_pattern', models.JSONField(default=list)),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='17:00')),
                ('total_units', models.IntegerField(default=0, verbose_name='総単位数')),
                ('within_units', models.IntegerField(default=0, verbose_name='区分支給限度内単位数')),
                ('over_units', models.IntegerField(default=0, verbose_name='限度超過単位数')),
                ('total_cost', models.IntegerField(default=0, verbose_name='総費用')),
                ('benefit_amount', models.IntegerField(default=0, verbose_name='給付費請求額')),
                ('user_share_amount', models.IntegerField(default=0, verbose_name='利用者負担額')),
                ('over_cost', models.IntegerField(default=0, verbose_name='限度超過分の総額')),
                ('over_user_share', models.IntegerField(default=0, verbose_name='限度超過分の自己負担額')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='ServiceRecord',
        ),
    ]
