# Generated by Django 6.0.7 on 2026-07-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_servicemonthlyrecord_delete_servicerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='slack_app_token',
            field=models.CharField(blank=True, default='', help_text='xapp- で始まるトークン（Socket Mode接続用）', max_length=100, verbose_name='Slack Appトークン'),
        ),
        migrations.AddField(
            model_name='office',
            name='slack_bot_token',
            field=models.CharField(blank=True, default='', help_text='xoxb- で始まるトークン。出退勤ボタン・日報プロンプトの送信に使用', max_length=100, verbose_name='Slack Botトークン'),
        ),
    ]
