# Generated by Django 6.0.3 on 2026-07-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_office_slack_app_token_office_slack_bot_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='slack_app_token',
            new_name='_slack_app_token',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='slack_bot_token',
            new_name='_slack_bot_token',
        ),
    ]
