# Generated by Django 6.0.6 on 2026-08-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_rename_slack_app_token_office__slack_app_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='month',
            field=models.IntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], default=8),
        ),
    ]
