# Generated by Django 6.0.6 on 2026-08-11 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_alter_serviceplan_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hogo_number', models.CharField(max_length=8, verbose_name='保護番号')),
                ('recipient_number', models.CharField(max_length=10, verbose_name='受給者番号')),
                ('start_date', models.DateField(verbose_name='適用開始日')),
                ('end_date', models.DateField(verbose_name='適用終了日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_assistance', to='dashboard.user')),
            ],
        ),
    ]
