# Generated by Django 6.0.6 on 2026-08-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_publicassistance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addonservice',
            options={'verbose_name_plural': '加算マスタ'},
        ),
        migrations.AlterModelOptions(
            name='caremanager',
            options={'verbose_name_plural': 'ケアマネジャー'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': '介護認定情報'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name_plural': '保険者（地域）マスタ'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name_plural': '事務所マスタ'},
        ),
        migrations.AlterModelOptions(
            name='publicassistance',
            options={'verbose_name_plural': '生活保護情報'},
        ),
        migrations.AlterModelOptions(
            name='servicemaster',
            options={'verbose_name_plural': '利用サービス マスタ'},
        ),
        migrations.AlterModelOptions(
            name='servicemonthlyrecord',
            options={'verbose_name_plural': '月間提供表'},
        ),
        migrations.AlterModelOptions(
            name='serviceplan',
            options={'verbose_name_plural': 'サービス利用計画'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '利用者'},
        ),
        migrations.AlterField(
            model_name='caremanager',
            name='care_management_office_number',
            field=models.CharField(max_length=10, verbose_name='居宅介護支援事業所番号'),
        ),
        migrations.AlterField(
            model_name='caremanager',
            name='care_manager_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='居宅介護支援専門員番号'),
        ),
        migrations.AlterField(
            model_name='publicassistance',
            name='hogo_number',
            field=models.CharField(help_text='地区番号 + 世帯番号', max_length=8, verbose_name='保護番号'),
        ),
    ]
