# Generated by Django 6.0.6 on 2026-08-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_alter_addonservice_options_alter_caremanager_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='benefit_rate',
        ),
    ]
