# Generated by Django 6.0.6 on 2026-08-16 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_remove_user_benefit_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-limit_start', '-created_at'], 'verbose_name_plural': '介護認定情報'},
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効フラグ'),
        ),
    ]
