# Generated by Django 6.0.6 on 2026-08-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_alter_certificate_options_certificate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='care_level',
            field=models.CharField(blank=True, choices=[('要介護1', '要介護1'), ('要介護2', '要介護2'), ('要介護3', '要介護3'), ('要介護4', '要介護4'), ('要介護5', '要介護5')], max_length=10, null=True),
        ),
    ]
