# Generated by Django 6.0.6 on 2026-08-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_serviceplan_care_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemonthlyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_records', to='dashboard.user'),
        ),
    ]
