# Generated by Django 6.0.6 on 2026-08-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_alter_servicemonthlyrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemonthlyrecord',
            name='public_amount',
            field=models.IntegerField(default=0, verbose_name='公費請求額'),
        ),
    ]
