# Generated by Django 6.0.6 on 2026-09-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_alter_serviceplan_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemonthlyrecord',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.office', verbose_name='事業所'),
            preserve_default=False,
        ),
    ]
