# Generated by Django 6.0.6 on 2026-09-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_servicemonthlyrecord_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='monthly_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='dashboard.servicemonthlyrecord'),
        ),
        migrations.AlterField(
            model_name='servicemonthlyrecord',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.office', verbose_name='サービス提供の事業所'),
        ),
    ]
