# Generated by Django 6.0.6 on 2026-09-06 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_serviceplan_monthly_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='monthly_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='dashboard.servicemonthlyrecord'),
            preserve_default=False,
        ),
    ]
