# Generated by Django 6.0.6 on 2026-09-07 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_alter_serviceplan_monthly_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='cert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.certificate'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='end_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
