# Generated by Django 6.0.6 on 2026-09-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_serviceplan_cert_serviceplan_end_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='start_day',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='end_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='介護認定情報が月の中で変わる時に代わる日を記録'),
        ),
    ]
