# Generated by Django 6.0.3 on 2026-09-20 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_serviceplan_start_day_alter_serviceplan_end_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='care_manager',
        ),
        migrations.AlterField(
            model_name='caremanager',
            name='care_manager_number',
            field=models.CharField(default='', max_length=13, verbose_name='居宅介護支援専門員番号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicassistance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='生活保護情報が有効かどうかを示すフラグ。無効の場合は、利用者の生活保護情報として扱われません。', verbose_name='有効フラグ'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='care_level',
            field=models.CharField(choices=[('要介護1', '要介護1'), ('要介護2', '要介護2'), ('要介護3', '要介護3'), ('要介護4', '要介護4'), ('要介護5', '要介護5')], max_length=10, verbose_name='要介護状態区分'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='description',
            field=models.CharField(default='2026-03-01', max_length=100, verbose_name='サービス説明'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_code',
            field=models.CharField(max_length=20, verbose_name='サービスコード'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(max_length=20, verbose_name='サービス名'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='stay_time_category',
            field=models.CharField(choices=[('<3', '3時間以下'), ('3-4', '3以上-4未満'), ('4-5', '4以上-5未満'), ('5-6', '5以上-6未満'), ('6-7', '6以上-7未満'), ('7-8', '7以上-8未満'), ('8-9', '8以上-9未満')], max_length=20, verbose_name='滞在時間区分'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='unit',
            field=models.IntegerField(verbose_name='単位'),
        ),
        migrations.CreateModel(
            name='UseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='被保険者氏名')),
                ('name_kana', models.CharField(max_length=100, verbose_name='フリガナ')),
                ('insured_number', models.CharField(max_length=10, unique=True, verbose_name='被保険者番号')),
                ('date_of_birth', models.DateField(verbose_name='生年月日')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=10, verbose_name='性別')),
                ('notes', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('care_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.caremanager', verbose_name='ケアマネージャー')),
            ],
            options={
                'verbose_name_plural': '利用者',
            },
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='dashboard.useuser', verbose_name='利用者'),
        ),
        migrations.AlterField(
            model_name='publicassistance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_assistance', to='dashboard.useuser', verbose_name='利用者'),
        ),
        migrations.AlterField(
            model_name='servicemonthlyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_records', to='dashboard.useuser'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.useuser'),
        ),
    ]
