# Generated by Django 6.0.3 on 2026-09-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_remove_user_care_manager_and_more'),
        ('diary', '0005_alter_entry_user'),
        ('employees', '0006_alter_assignment_user_alter_shiftpattern_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
