# Generated by Django 6.0.3 on 2026-09-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caremanager',
            name='care_manager_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='居宅介護支援専門員番号'),
        ),
    ]
