# Generated by Django 6.0.3 on 2026-09-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_alter_caremanager_care_manager_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='service_type_code',
            field=models.IntegerField(choices=[(78, '地域密着型通所介護'), (79, '通所介護（通常規模）'), (80, '通所介護（大規模Ⅰ）'), (81, '通所介護（大規模Ⅱ）')], default=78, help_text='地域密着型通所介護 → 78\n                    通所介護（通常規模） → 79\n                    通所介護（大規模Ⅰ） → 80\n                    通所介護（大規模Ⅱ） → 81', verbose_name='種類コード'),
        ),
    ]
