# Generated by Django 6.0.3 on 2026-09-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_alter_office_service_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonservice',
            name='is_tax',
            field=models.BooleanField(default=False, verbose_name='課税'),
        ),
    ]
