# Generated by Django 6.0.3 on 2026-09-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_alter_addonservice_is_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonservice',
            name='service_type_code',
            field=models.IntegerField(blank=True, choices=[(78, '地域密着型通所介護'), (79, '通所介護（通常規模）'), (80, '通所介護（大規模Ⅰ）'), (81, '通所介護（大規模Ⅱ）')], null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='care_level_changed_at',
            field=models.DateField(blank=True, help_text='次の介護認定の更新時に設定される日付', null=True, verbose_name='要介護状態区分変更日'),
        ),
    ]
