# Generated by Django 6.0.3 on 2026-09-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_addonservice_service_type_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemonthlyrecord',
            name='actual_count',
            field=models.IntegerField(default=0, verbose_name='実績日数'),
        ),
        migrations.AddField(
            model_name='servicemonthlyrecord',
            name='service_units',
            field=models.IntegerField(default=0, verbose_name='サービス＋加算などの単位数合計'),
        ),
        migrations.AlterField(
            model_name='servicemonthlyrecord',
            name='total_units',
            field=models.IntegerField(default=0, help_text='サービス＋加算等の総単位', verbose_name='総単位数'),
        ),
    ]
